import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...\n');

  // Create admin operator
  const adminPassword = await bcrypt.hash('admin123', 10);
  const admin = await prisma.operator.upsert({
    where: { email: 'admin@lucine.it' },
    update: {},
    create: {
      email: 'admin@lucine.it',
      passwordHash: adminPassword,
      name: 'Admin Lucine',
      role: 'ADMIN',
      isOnline: false,
    },
  });
  console.log('✅ Admin operator created:', admin.email);

  // Create regular operator
  const operatorPassword = await bcrypt.hash('operator123', 10);
  const operator = await prisma.operator.upsert({
    where: { email: 'mario.rossi@lucine.it' },
    update: {},
    create: {
      email: 'mario.rossi@lucine.it',
      passwordHash: operatorPassword,
      name: 'Mario Rossi',
      role: 'OPERATOR',
      isOnline: false,
      whatsappNumber: '+393331234567',
    },
  });
  console.log('✅ Operator created:', operator.email);

  // Create knowledge base items
  const kbItems = [
    {
      question: 'Dove posso parcheggiare?',
      answer: 'Il parcheggio consigliato è P5 dell\'Eremo, con navetta gratuita per le Lucine di Natale. È il più comodo e capiente. Ci sono anche i parcheggi P1 e P2 che sono gratuiti ma più limitati.',
      category: 'PARCHEGGIO',
    },
    {
      question: 'Quanto costano i biglietti?',
      answer: 'I biglietti per le Lucine di Natale costano €15 per gli adulti e €8 per i bambini (3-12 anni). I bambini sotto i 3 anni entrano gratis. Sono disponibili anche pacchetti famiglia.',
      category: 'BIGLIETTI',
    },
    {
      question: 'Quali sono gli orari di apertura?',
      answer: 'Le Lucine di Natale sono aperte tutti i giorni dalle 17:00 alle 23:00 (ultimo ingresso ore 22:00). Il periodo di apertura va dal 25 novembre al 6 gennaio.',
      category: 'ORARI',
    },
    {
      question: 'È accessibile per disabili?',
      answer: 'Sì, il percorso delle Lucine di Natale è completamente accessibile per persone con disabilità motoria. Sono disponibili parcheggi dedicati e servizi igienici attrezzati.',
      category: 'ACCESSO',
    },
    {
      question: 'Ci sono ristoranti o bar?',
      answer: 'Sì, lungo il percorso troverai diversi punti ristoro con cioccolata calda, vin brulé, dolci tipici e street food. È presente anche un\'area ristorante con menù completo.',
      category: 'SERVIZI',
    },
  ];

  for (const item of kbItems) {
    const created = await prisma.knowledgeItem.upsert({
      where: {
        id: item.question.substring(0, 36), // Use consistent ID
      },
      update: {},
      create: {
        question: item.question,
        answer: item.answer,
        category: item.category,
        isActive: true,
        createdBy: admin.id,
        // Note: embedding will be generated by API on first use
      },
    });
    console.log('✅ KB item created:', created.question);
  }

  // Create system settings (value as Json)
  const settings = [
    {
      key: 'CHAT_ENABLED',
      value: true,
      description: 'Enable/disable chat widget',
      category: 'general'
    },
    {
      key: 'AI_ENABLED',
      value: true,
      description: 'Enable/disable AI responses',
      category: 'ai'
    },
    {
      key: 'AI_CONFIDENCE_THRESHOLD',
      value: 0.7,
      description: 'Confidence threshold for AI responses (0-1)',
      category: 'ai'
    },
    {
      key: 'WELCOME_MESSAGE',
      value: 'Ciao! Sono Lucy, il tuo assistente virtuale 👋 Come posso aiutarti?',
      description: 'Welcome message for new chats',
      category: 'chat'
    },
    {
      key: 'OPERATOR_TIMEOUT_MINUTES',
      value: 5,
      description: 'Minutes before operator timeout',
      category: 'chat'
    },
    {
      key: 'MAX_CONCURRENT_CHATS_PER_OPERATOR',
      value: 3,
      description: 'Maximum concurrent chats per operator',
      category: 'chat'
    },
  ];

  for (const setting of settings) {
    await prisma.systemSettings.upsert({
      where: { key: setting.key },
      update: {
        value: setting.value,
        description: setting.description,
        category: setting.category,
      },
      create: setting,
    });
    console.log('✅ System setting created:', setting.key);
  }

  console.log('\n✅ Seed completed successfully!');
  console.log('\n📝 Login credentials:');
  console.log('   Admin:    admin@lucine.it / admin123');
  console.log('   Operator: mario.rossi@lucine.it / operator123');
}

main()
  .catch((e) => {
    console.error('❌ Error during seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
